### ISSUE TITLE
`getenv` result is modified

### ISSUE THREAD

**Issue by mpan-pl** [alyptik/cepl#3]
`main.c:328`: `char *tmp_str = strcat(strcat(getenv("HOME"), "/"), HIST_NAME);`
The result of `getenv` shouldn’t be modified, but two consecutive `strcat` calls modify it.

In my case the next environment variable available in the variables list is overwritten/damaged.

Ignoring above, no memory is reserved for appending strings with `strcat`.

**Comment by alyptik** [comment]
Fixed UB with nested `strcat()` calls in [a4b4582](https://github.com/alyptik/cepl/commit/a4b4582287a31ae75a7e8af87acf0cca02695cc5)
