### ISSUE TITLE
LICENSE was replaced with a tarball with pre-compiled object files

### ISSUE THREAD

**Issue by gonsoos** [alyptik/cepl#8]
Why did you replace the `LICENSE` file with a tarball with pre-compiled object files in https://github.com/alyptik/cepl/commit/5db00d5202172b18d580f4103776baa7dd896c26?

Previously, I had informed you about pre-compiled object files being present in the now deleted release tarball for v8.4.0 IIRC.

**Comment by alyptik** [comment]
Wow, I have no idea how that happened... It has been fixed.
